# Generated by Django 5.0.6 on 2024-06-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=800, null=True, unique=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'link')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1800, null=True)),
                ('image_cover', models.CharField(blank=True, max_length=1800, null=True)),
                ('caption', models.CharField(blank=True, max_length=800, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_reviews.product', to_field='product_no')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_name', models.CharField(blank=True, max_length=245, null=True)),
                ('Country', models.CharField(blank=True, max_length=228, null=True)),
                ('Review_time', models.CharField(blank=True, max_length=228, null=True)),
                ('Review_text', models.TextField()),
                ('Review_rating', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_reviews.product', to_field='product_no')),
            ],
        ),
    ]
