# Generated by Django 5.0.6 on 2024-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_reviews', '0004_review_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naive_bayes_classifier', models.FileField(upload_to='models/')),
                ('vectorizer', models.FileField(upload_to='models/')),
            ],
        ),
        migrations.CreateModel(
            name='Amazon_login_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=245, null=True)),
                ('password', models.CharField(blank=True, max_length=245, null=True)),
            ],
        ),
    ]
