# Generated by Django 5.0.6 on 2024-06-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_reviews', '0005_ai_model_amazon_login_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_login_details',
            old_name='username',
            new_name='email',
        ),
    ]
